Repository wso2/docs-mg, pull requests merged in 2020-09, with the labels that each got.

#54 Fix Formatting issues
  en/docs/assets/img/install-and-setup/Environment-variables.png
  en/docs/assets/img/install-and-setup/add-new-variable.png
  en/docs/assets/img/install-and-setup/edit-environment-variable.png
  en/docs/assets/img/install-and-setup/select-path-system-var.png
  en/docs/getting-started/quick-start-guide/quick-start-guide-binary.md
  en/docs/how-tos/endpoints/defining-a-backend-security-scheme.md
  en/docs/how-tos/extensions/adding-extension-points.md
  en/docs/install-and-setup/install-on-vm.md
  en/mkdocs.yml
Labels: PR/review-pending-resolution, PR/tc-review-complete

#58 Fix FAQ documentation
  en/docs/faqs.md
Labels: PR/review-comments-resolved, PR/review-pending-resolution, PR/tc-review-complete

#52 Format overriding endpoints doc
  en/docs/how-tos/endpoints/overriding-endpoint-information/overriding-endpoints-for-imported-apis.md
  en/docs/reference/configurations/deployment.toml-for-docker.md
  en/docs/reference/configurations/deployment.toml-for-kubernetes.md
Labels: PR/review-comments-resolved, PR/tc-review-complete

#59 Update docs
  en/docs/concepts/revoked-tokens.md
  en/docs/faqs.md
  en/docs/getting-started/about-this-release.md
  en/docs/getting-started/quick-start-guide/quick-start-guide-binary.md
  en/docs/getting-started/quick-start-guide/quick-start-guide-docker.md
  en/docs/how-tos/adding-apis/importing-a-group-of-apis-from-wso2-api-manager.md
  en/docs/how-tos/adding-apis/importing-a-single-api-from-wso2-api-manager.md
  en/docs/how-tos/adding-apis/using-an-openapi-definition.md
  en/docs/how-tos/http-2.0.md
  en/docs/how-tos/rate-limiting/distributed-throttling.md
  en/docs/how-tos/rate-limiting/rate-limiting-overview.md
  en/docs/how-tos/security/api-authentication/api-authentication.md
  en/docs/how-tos/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-jwt-self-contained-jwt.md
  en/docs/how-tos/security/importing-certificates-to-the-api-microgateway-truststore.md
  en/docs/install-and-setup/configuration-for-wso2-api-manager.md
  en/docs/install-and-setup/migrating-from-previous-versions.md
  en/docs/reference/configurations/deployment.toml-for-docker.md
  en/docs/reference/configurations/micro-gw.conf.md
  en/docs/reference/project-directory.md
Labels: PR/review-comments-resolved, PR/review-pending-resolution, PR/tc-review-complete

#44 Add conditional throttling howto page
  en/docs/assets/img/how-tos/distributed-throttling.png
  en/docs/concepts/rate-limiting.md
  en/docs/how-tos/passing-enduser-attributes-to-the-backend-using-jwt.md
  en/docs/how-tos/rate-limiting/adding-throttling-policies.md
  en/docs/how-tos/rate-limiting/distributed-throttling.md
  en/docs/how-tos/rate-limiting/rate-limiting-overview.md
  en/mkdocs.yml
Labels: PR/review-pending-resolution, PR/tc-review-complete, PR/technical-review-complete, Priority/Normal
